force-app/main/default/objects/Event_Staging_Record__c/Event_Staging_Record__c.object-meta.xml
<CustomObject>
    <label>Event Staging Record</label>
    <nameField>
        <displayFormat>Evt-{00000000}</displayFormat>
        <label>Event Record Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Staging Records</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Staging_Record__c/fields/Error_Message__c.field-meta.xml
<CustomField>
    <fullName>Error_Message__c</fullName>
    <description>Error message of the event process.</description>
    <label>Error Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Event_Staging_Record__c/fields/Status_Code__c.field-meta.xml
<CustomField>
    <fullName>Status_Code__c</fullName>
    <description>The status code returned from the event process refers to the HTTP StatusCode.</description>
    <label>Status Code</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/EventHandler.cls
// Salesforce REST Endpoint: /services/apexrest/tmf-api/eventHandler
@RestResource(urlMapping='/tmf-api/eventHandler')
global without sharing class EventHandler {
    global EventHandler() {

    }

    @HttpPost
    global static void processEvent() {
        RestResponse resp = RestContext.response;

        EventSyncEngine evtEngine = new EventSyncEngine();
        String eventPayload = RestContext.Request.requestBody.toString();

        try {
            Event_Staging_Record__c stagingRec = evtEngine.processEvent(eventPayload);
            resp.statusCode = (Integer)stagingRec.Status_Code__c;
            if (resp.statusCode == 200 || resp.statusCode == 201 || resp.statusCode == 202) {
	            resp.responseBody = Blob.valueOf(stagingRec.Id);
            } else {
                resp.responseBody = Blob.valueOf(stagingRec.Error_Message__c);
            }
        } catch (Exception ex) {
            System.debug(ex.getMessage());
            resp.statusCode = 500;
            resp.responseBody = Blob.valueOf(EventSyncEngine.getErrorMessage(ex));
        }

    }
}